title: "Esto es Peñarol"
author: Juan Izquierdo
email: jpizquierdo19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sos mi locura y pasión, tuya es mi vida penarol como decirte,
   de una vez cuanto te quieeeero!

# social links
twitter_username: juanpeizq
github_username:  juanpedroizquierdo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
